apiVersion: tower.ansible.com/v1alpha1
kind: AnsibleCredential
metadata:
  name: machine-credentials
  namespace: aap
spec:
  name: 'Linux user/pass'
  type: Machine
  organization: Default
  connection_secret: controller-access
  ssh_username: 'redhat1'
  ssh_password: 'redhat1'