apiVersion: tower.ansible.com/v1alpha1
kind: AnsibleInventory
metadata:
  name: ocp-virt-inventory
  namespace: aap
spec:
  connection_secret: controller-access
  name: OCP Virt
  organization: Default
  state: present