apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: demo-application-set
spec:
  generators:
    - list:
        elements:
          - name: demo-operators
            path: gitops/operators
            syncWave: "1"
          - name: demo-crds
            path: gitops/crd-instances
            syncWave: "2"
  template:
    metadata:
      name: "{{name}}"
      annotations:
        argocd.argoproj.io/sync-wave: "{{syncWave}}"
        argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    spec:
      project: default
      source:
        repoURL: 'https://github.com/pablo-preciado/aap-ocpv'
        targetRevision: main
        path: "{{path}}"
      destination:
        server: 'https://kubernetes.default.svc'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true