apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-operators
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: 'https://github.com/pablo-preciado/aap-ocpv'
    targetRevision: main
    path: gitops/operators
  destination:
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
