kind: Secret
apiVersion: v1
metadata:
  name: '{{ .Values.keycloakSecret.secretName }}'
  namespace: '{{ .Values.keycloakSecret.namespaceName }}'
data:
  tls.crt: '{{ .Values.keycloakSecret.crtFile | b64enc }}'
  tls.key: '{{ .Values.keycloakSecret.keyFile | b64enc }}'
type: kubernetes.io/tls