- hosts: localhost
  tasks:

  - name: Create project
    redhat.openshift.k8s:
      state: present
      definition:
        apiVersion: project.openshift.io/v1
        kind: Project
        metadata:
          name: workloads

  - name: Create RHEL9 virtual machine
    redhat.openshift_virtualization.kubevirt_vm:
      state: present
      name: rhel9-httpd
      namespace: workloads
      labels:
        app: httpd
      instancetype:
        name: u1.medium
      preference:
        name: rhel.9
      data_volume_templates:
        - metadata:
            name: rhel9-containerdisk
          spec:
            sourceRef:
              name: rhel9
              kind: DataSource
              namespace: openshift-virtualization-os-images
            storage:
              resources:
                requests:
                  storage: 30Gi
      spec:
        domain:
          devices:
            interfaces:
              - name: default
                masquerade: {}
        networks:
          - name: default
            pod: {}
        volumes:
          - dataVolume:    
              name: rhel9-containerdisk
            name: rootdisk
          - cloudInitNoCloud:
              userData: |-
                #cloud-config
                # The default username is: fedora
                ssh_authorized_keys:
                - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC4ukkAeRFwv3MwFMQN5CQsIpRl+iPOnSrmR9hvirODi9hl3CUdSVGJKMF8isIyPUishNQSG/lD6NHKyGOV8Sda0OzSUmkV13AfM+jd1NCD0/9swvw7YeQnNlqKHJVtztLIOjRmk9MFtgSnGQnx1JVd0VU98YQSBfnRaADyIZ5ePac9FECb/ocCmKtC+edmtkAGJze+K6nDZfiE7pozXvz92K4CeSjDFiX3julb3hITZPp72EexhrhzQBzNNLcvZ3czMopwS0EiwQ8fCZOr70UYvITwH6xEc/nDiFMsB03IuyJ8XwSUKR3Om/aU0sby8vwLo6zQtgJQAMhD+WL3rdsCsYDvi+aaVfbp3okx5MeLCs2c00H/2dZatYRx9odbxyCccl3YICKApbAZYNWVmvMWfRddMoxTJF3g4KZblgptoOABsHs2tXCRGxLksbU2XAqaYt4oT4lCRl9qVZXRa0jqsnOqd8+0knf1JncVi9BGFq1oCDzgfbG3EOnBdjR5MH8= preciado@toolbx
            name: cloudinit
  
  - name: Wait for virtual machine IP to be populated
    kubernetes.core.k8s_info:
      api_version: kubevirt.io/v1
      kind: VirtualMachineInstance
      name: rhel9-httpd
      namespace: workloads
    register: vmi
    retries: 60
    delay: 10
    until: (vmi.resources[0].status.interfaces[0]['ipAddress'] | default('')) | length > 0
