- name: Register and add jboss repos for all servers in namespace workloads
  hosts: namespace_workloads
  become: true
  tasks:
    - name: Register to Red Hat
      redhat_subscription:
        state: present
        username: "{{ rhsm_username }}"
        password: "{{ rhsm_password }}"
        auto_attach: true

    - name: Enable jboss repo
      command: 'subscription-manager repos --enable=jb-eap-8.0-for-rhel-9-x86_64-rpms'