- name: Register and add jboss repos for all servers in namespace workloads
  hosts: namespace_workloads
  become: true
  tasks:
    - name: Register to Red Hat
      redhat_subscription:
        state: present
        username: "{{ rhsm_username }}"
        password: "{{ rhsm_password }}"
        auto_attach: true

    - name: Enable jboss repo in RHSM
      community.general.rhsm_repository:
        name: jb-eap-8-for-rhel-9-x86_64-rpms
        state: enabled

    - name: Enable JBoss EAP 8 repository
      ansible.builtin.yum_repository:
        name: jb-eap-8-for-rhel-9-x86_64-rpms
        description: JBoss EAP 8 for RHEL 9
        enabled: true