---
apiVersion: v1
kind: Namespace
metadata:
  name: aap
  labels:
    argocd.argoproj.io/managed-by: openshift-gitops
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: my-aap-operatorgroup
  namespace: aap
spec:
  upgradeStrategy: Default
  targetNamespaces:
    - aap
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/ansible-automation-platform-operator.aap: ''
  name: ansible-automation-platform-operator
  namespace: aap
spec:
  installPlanApproval: Automatic
  name: ansible-automation-platform-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace